app/code/community/OnePica/AvaTax/Model/Sales/Quote/Address/Total/Tax.php

Solves issue when cart contains only virtual products and no shipping address.

Re #16 Check the current address for actionability.

---

modman

Added 'onepica' to app/design pathes.

Fixed pathes

---

app/code/community/OnePica/AvaTax/etc/system.xml

- added 'can_be_empty' parameter to fields which can be empty

AV-402: AvaTax Config. User is not able to make fields "Filter Requests by Region", "Log Type", "Required Fields" empty

---

app/code/community/OnePica/AvaTax/etc/system.xml

AV-405: AvaTax Config. AvaTax Settings. Field "Required Fileds" has incorrect text

---

app/code/community/OnePica/AvaTax/Model/Avatax/Abstract.php

- changed the way of getting customer group id

AV-553: Tax is not recalculated if change customer group while place order via admin

---

app/code/community/OnePica/AvaTax/Helper/Data.php
app/code/community/OnePica/AvaTax/Model/Avatax/Abstract.php
app/code/community/OnePica/AvaTax/Model/Avatax/Estimate.php
app/code/community/OnePica/AvaTax/Model/Avatax/Invoice.php
app/code/community/OnePica/AvaTax/etc/system.xml

Implemented taxability based on UPC

Ava tax/feature/av 29

---

app/code/community/OnePica/AvaTax/Block/Adminhtml/Export/Log/Grid.php
app/code/community/OnePica/AvaTax/Helper/Data.php

- fixed displaying log type in grid

AV-550: AvaTax Action Log table. Types of Logs that are not selected in AvaTax Configuration are not displayed in Log table

---

app/code/community/OnePica/AvaTax/Model/Avatax/Invoice.php

- added converting date, taking into account the current time zone

Implemented AV-583: Doc Date Still Incorrect on Sync from Magento

---

app/code/community/OnePica/AvaTax/Model/Observer.php

- fixed adding invoice to queue

Implemented AV-648: Investigate and Resolve problem in condition

---

app/code/community/OnePica/AvaTax/Model/Sales/Quote/Address/Total/Tax.php

AV-755: Admin Order Placing. Store with currency different from default. Tax is not converted to needed currency

---

app/code/community/OnePica/AvaTax/Model/Avatax/Abstract.php
app/code/community/OnePica/AvaTax/Model/Avatax/Estimate.php

AV-768: Multiple Checkout. Get Tax Log. VAT ID of any order placed during multiple checkout equals VAT entered for first order

---

app/code/community/OnePica/AvaTax/Helper/Address.php
app/code/community/OnePica/AvaTax/Helper/Config.php
app/code/community/OnePica/AvaTax/Helper/Data.php
app/code/community/OnePica/AvaTax/Helper/Errors.php
app/code/community/OnePica/AvaTax/Helper/Lib.php
app/code/community/OnePica/AvaTax/Model/Adminhtml/Config.php
app/code/community/OnePica/AvaTax/Model/Adminhtml/Sales/Order/Create.php
app/code/community/OnePica/AvaTax/Model/Avatax/Abstract.php
app/code/community/OnePica/AvaTax/Model/Avatax/Address.php
app/code/community/OnePica/AvaTax/Model/Avatax/Estimate.php
app/code/community/OnePica/AvaTax/Model/Avatax/Invoice.php
app/code/community/OnePica/AvaTax/Model/Observer.php
app/code/community/OnePica/AvaTax/Model/Sales/Quote/Address.php
app/code/community/OnePica/AvaTax/Model/Sales/Quote/Address/Total/Grand.php
app/code/community/OnePica/AvaTax/Model/Sales/Quote/Address/Total/Tax.php

AVTNG-60 Refactoring avatax helper

---

app/code/community/OnePica/AvaTax/Helper/Config.php
app/code/community/OnePica/AvaTax/Model/Calculator.php
app/code/community/OnePica/AvaTax/Model/Service/Abstract.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax/Abstract.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax/Estimate.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax/Tax.php

AVTNG-62 Code changes due to AVTNG-28 and AVTNG-60

AVTNG-62 Code changes due to AVTNG-28 and AVTNG-60

---

app/code/community/OnePica/AvaTax/Model/Calculator.php
app/code/community/OnePica/AvaTax/Model/Records/Queue/Process.php
app/code/community/OnePica/AvaTax/Model/Service/Abstract.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax/Abstract.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax/Estimate.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax/Invoice.php

AVTNG-46: Implement tax creditmemo and invoice functionality

AVTNG-46: Implement tax creditmemo and invoice functionality

---

app/code/community/OnePica/AvaTax/Model/Calculator.php
app/code/community/OnePica/AvaTax/Model/Sales/Quote/Address.php
app/code/community/OnePica/AvaTax/Model/Service/Abstract.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax/Abstract.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax/Address.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax/Invoice.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax/Tax.php
app/code/community/OnePica/AvaTax/Model/Validator.php

AVTNG-44 Implement tax address validation functionality

AVTNG-44 Implement tax address validation functionality

---

app/code/community/OnePica/AvaTax/Helper/Config.php
app/code/community/OnePica/AvaTax/Model/Calculator.php
app/code/community/OnePica/AvaTax/Model/Service.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax/Abstract.php
app/code/community/OnePica/AvaTax/Model/Source/Avatax/Actions.php
app/code/community/OnePica/AvaTax/Model/Source/Avatax/Logtype.php
app/code/community/OnePica/AvaTax/Model/Source/Avatax16/Actions.php
app/code/community/OnePica/AvaTax/Model/Source/Avatax16/Logtype.php
app/code/community/OnePica/AvaTax/Model/Validator.php
app/code/community/OnePica/AvaTax/etc/config.xml

AVTNG-65 Implement required fileds in admin config for avatax16 API 

---

app/code/community/OnePica/AvaTax/Helper/Config.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax16/Config.php
app/code/community/OnePica/AvaTax/etc/system.xml

AVTNG-66 Implement config class for avatax16 API

AVTNG-66 Implement config class for avatax16 API

---

app/code/community/OnePica/AvaTax/Helper/Config.php
app/code/community/OnePica/AvaTax/Model/Calculator.php
app/code/community/OnePica/AvaTax/Model/Sales/Quote/Address.php
app/code/community/OnePica/AvaTax/Model/Service.php
app/code/community/OnePica/AvaTax/Model/Service/Abstract.php
app/code/community/OnePica/AvaTax/Model/Service/Abstract/Tools.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax/Abstract.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax/Address.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax/Invoice.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax16.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax16/Abstract.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax16/Address.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax16/Config.php
app/code/community/OnePica/AvaTax/etc/config.xml
app/code/community/OnePica/AvaTax/etc/system.xml

feature/avtng-68 Implement tax address validation functionality

Feature/avtng-68 Implement tax address validation functionality

---

app/code/community/OnePica/AvaTax/Model/Service/Avatax16/Tax.php

- Fixed sending redundend request

Implemented AVTNG-91: Two similar calculation requests are sent.

---

app/code/community/OnePica/AvaTax/Model/Service/Avatax16/Tax.php

AVTNG-97: Currency is not sent and vendor is incorrect in required header level data elements of Transaction and Calculation Requests

---

app/code/community/OnePica/AvaTax/Helper/Calculation.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax/Abstract.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax16/Tax.php

- added possibility to send customer code for Avatax16

AVTNG-80: AvaTax Code is not sent in GetTax request.

---

app/code/community/OnePica/AvaTax/Model/Observer.php

AVTNG-714: if user adds product to shopping cart after clearing browser cache and cookie, Subtotal and Grand Total values equal 0

---

app/code/community/OnePica/AvaTax/Helper/Calculation.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax/Abstract.php
app/code/community/OnePica/AvaTax/Model/Service/Avatax16/Tax.php

- Fixed retrieving customer opAvaTaxCode for transaction request

AVTNG-730: defaultBuyerType is not sent in Transaction Request; queue cannot be sent to Avalara admin

---

app/code/community/OnePica/AvaTax/Model/Avatax/Invoice.php
app/code/community/OnePica/AvaTax/etc/config.xml

AV-846: Incorrect converting date for Invoice and Creditmemo

---

app/code/community/OnePica/AvaTax/Model/Service/Avatax16/Ping.php

- Added error message in case if response not contain error message

AVTNG-737: Empty error message is displayed  after saving config with invalid Key for AvaTax Connection Settings.

---

app/code/community/OnePica/AvaTax/Model/Service/Avatax16/Estimate.php

- Added skipping handling lines without tax

Implemented AVTNG-739: Error messages is displayed when trying to create order from admin panel

---

app/code/community/OnePica/AvaTax/Model/Service/Avatax16/Estimate.php

- Added retrieving jurisdiction rates from line

Implemented AVTNG-766: Tax Rate calculations. Rates are shown as 0% on Storefront if tax was calculated for > 1 jurisdiction

---

app/code/community/OnePica/AvaTax/etc/config.xml

- Set default value for address_validation

Implemented AVTNG-784: Address Validation should be enabled by default

---

app/code/community/OnePica/AvaTax/Model/Service/Avatax/Abstract.php

Implemented AV-1273: Request header. CompanyCode value is not sent

---

app/code/community/OnePica/AvaTax/Model/Records/Log.php

Implemented AV-1287: License key is not masked in error ping log entries

---

app/code/community/OnePica/AvaTax/Helper/RequestFilter.php
app/code/community/OnePica/AvaTax/Model/Sales/Quote/Address/Total/Tax.php
app/code/community/OnePica/AvaTax/etc/config.xml
app/code/community/OnePica/AvaTax/etc/system.xml

- added possiblity to limit requests

Implemented AV-815: Add possibility to limit GetTax request

---

app/code/community/OnePica/AvaTax/Model/Adminhtml/Config.php
app/code/community/OnePica/AvaTax/etc/config.xml
app/code/community/OnePica/AvaTax/etc/system.xml

Implemented AV-1492: Shop up plugin version in System configuration
